# Keepalived idm2

vrrp_script chk_haproxy {
    script "/usr/bin/pgrep haproxy"
    interval 2
    fall 2
    rise 1
    weight -30
}

vrrp_instance VI_WEB {
    state BACKUP
    interface enp0s8
    virtual_router_id 74
    priority 100
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass <REDACTED>
    }

    unicast_src_ip 192.168.74.12
    unicast_peer {
        192.168.74.11
    }

    virtual_ipaddress {
        192.168.74.100/24 dev enp0s8
    }

    track_script {
        chk_haproxy
    }
}
