# krb5.conf 

[libdefaults]
    default_realm = FIS.EPN.EC
    dns_lookup_kdc = false
    dns_lookup_realm = false
    ticket_lifetime = 24h
    forwardable = true

[realms]
    FIS.EPN.EC = {
        kdc = kdc1.fis.epn.ec
        kdc = kdc2.fis.epn.ec
        admin_server = kdc1.fis.epn.ec
    }

[domain_realm]
    .fis.epn.ec = FIS.EPN.EC
    fis.epn.ec = FIS.EPN.EC
