[libdefaults]
    default_realm = FIS.EPN.EC
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    forwardable = true
    rdns = false

[realms]
    FIS.EPN.EC = {
        kdc = kdc1.fis.epn.ec
        admin_server = kdc1.fis.epn.ec
        default_domain = fis.epn.ec
    }

[domain_realm]
    .fis.epn.ec = FIS.EPN.EC
    fis.epn.ec = FIS.EPN.EC
